import { readFileSync, writeFileSync } from "node:fs";
import Whop from "@whop/sdk";

const DEMO_EMAIL = "you@example.com";

const ROOT = new URL("../", import.meta.url);
const env = Object.fromEntries(
  readFileSync(new URL(".env.local", ROOT), "utf8")
    .split("\n")
    .filter((line) => line.includes("=") && !line.startsWith("#"))
    .map((line) => {
      const i = line.indexOf("=");
      return [line.slice(0, i).trim(), line.slice(i + 1).trim()];
    }),
);

const whop = new Whop({
  apiKey: env.WHOP_COMPANY_API_KEY,
  baseURL:
    env.WHOP_SANDBOX === "true"
      ? "https://sandbox-api.whop.com/api/v1"
      : "https://api.whop.com/api/v1",
});
const CID = env.WHOP_COMPANY_ID;
const CHAT_APP_ID = "app_xml5hbizmZPgUT";

const demoEmail = (tag) => DEMO_EMAIL.replace("@", `+orbit${tag}@`);
const demoUsers = [];
for (const name of ["Ava Chen", "Ben Ortiz", "Cara Lee"]) {
  const tag = name.split(" ")[0].toLowerCase();
  const child = await whop.companies.create({
    email: demoEmail(tag),
    parent_company_id: CID,
    title: name,
    send_customer_emails: false,
    metadata: { internal_user_id: `demo_${tag}` },
  });
  const userId = child.owner_user.id;
  try {
    await whop.users.update(userId, { account_id: CID, name });
  } catch (e) {
    console.log(`  (name override skipped: ${e?.status ?? ""} ${e?.message ?? e})`);
  }
  demoUsers.push({ key: tag, name, userId });
  console.log(`${name} -> ${userId}`);
}
const [ava, ben, cara] = demoUsers;

const product = await whop.products.create({
  company_id: CID,
  title: "Orbit Community",
  description: "Membership that unlocks the Orbit community chat.",
  visibility: "visible",
});
console.log(`product -> ${product.id}`);

async function createChannel(name) {
  const exp = await whop.experiences.create({
    app_id: CHAT_APP_ID,
    company_id: CID,
    name,
    is_public: true,
  });
  await whop.experiences.attach(exp.id, { product_id: product.id });
  const channel = await whop.chatChannels.retrieve(exp.id);
  console.log(`${name} -> ${channel.id}`);
  return { id: channel.id, experienceId: exp.id, name };
}
const general = { ...(await createChannel("General")), readOnly: false };
const announcements = { ...(await createChannel("Announcements")), readOnly: true };
await whop.chatChannels.update(announcements.id, { who_can_post: "admins" });

const groupDm = await whop.dmChannels.create({
  with_user_ids: [ava.userId, ben.userId, cara.userId],
  company_id: CID,
  custom_name: "Orbit team",
});
const directDm = await whop.dmChannels.create({
  with_user_ids: [ava.userId, ben.userId],
  company_id: CID,
  custom_name: "Ava & Ben",
});
console.log(`DMs -> ${groupDm.id}, ${directDm.id}`);

const supportByUser = {};
for (const u of demoUsers) {
  const sc = await whop.supportChannels.create({
    company_id: CID,
    user_id: u.userId,
    custom_name: `${u.name.split(" ")[0]} - support`,
  });
  supportByUser[u.key] = sc.id;
  console.log(`support (${u.name}) -> ${sc.id}`);
}

const owner = await whop.companies.retrieve(CID);
const file = `// AUTO-GENERATED by scripts/setup.mjs. Do not edit by hand.

export interface DemoUser {
  key: string;
  name: string;
  userId: string;
}

export interface ChannelInfo {
  id: string;
  experienceId: string;
  name: string;
  readOnly: boolean;
}

export const companyId = ${JSON.stringify(CID)};
export const ownerUserId = ${JSON.stringify(owner.owner_user.id)};

export const demoUsers: DemoUser[] = ${JSON.stringify(demoUsers, null, 2)};

export const channels: Record<"general" | "announcements", ChannelInfo> = ${JSON.stringify({ general, announcements }, null, 2)};

export const dms: Record<"group" | "direct", { id: string; name: string }> = ${JSON.stringify(
  {
    group: { id: groupDm.id, name: "Orbit team" },
    direct: { id: directDm.id, name: "Ava & Ben" },
  },
  null,
  2,
)};

export const supportByUser: Record<string, string> = ${JSON.stringify(supportByUser, null, 2)};

export const productId = ${JSON.stringify(product.id)};

export const knownUserIds = demoUsers.map((u) => u.userId);
export function isKnownUser(userId: string): boolean {
  return knownUserIds.includes(userId);
}
`;
writeFileSync(new URL("constants/whop-ids.ts", ROOT), file);
console.log("wrote constants/whop-ids.ts");
