// AUTO-GENERATED by scripts/setup-sandbox.mjs. Do not edit by hand.
// These are placeholders: run `npm run setup` against your own sandbox
// company to provision the demo resources and regenerate this file.

export interface DemoUser {
  key: string;
  name: string;
  userId: string;
}

export interface ChannelInfo {
  id: string;
  experienceId: string;
  name: string;
  readOnly: boolean;
}

export const companyId = "biz_REPLACE_RUN_SETUP";
export const ownerUserId = "user_REPLACE_RUN_SETUP";

export const demoUsers: DemoUser[] = [
  {
    "key": "ava",
    "name": "Ava Chen",
    "userId": "user_REPLACE_AVA"
  },
  {
    "key": "ben",
    "name": "Ben Ortiz",
    "userId": "user_REPLACE_BEN"
  },
  {
    "key": "cara",
    "name": "Cara Lee",
    "userId": "user_REPLACE_CARA"
  }
];

export const channels: Record<"general" | "announcements", ChannelInfo> = {
  "general": {
    "id": "chat_feed_REPLACE_GENERAL",
    "experienceId": "exp_REPLACE_GENERAL",
    "name": "General",
    "readOnly": false
  },
  "announcements": {
    "id": "chat_feed_REPLACE_ANNOUNCEMENTS",
    "experienceId": "exp_REPLACE_ANNOUNCEMENTS",
    "name": "Announcements",
    "readOnly": true
  }
};

export const dms: Record<"group" | "direct", { id: string; name: string }> = {
  "group": {
    "id": "feed_REPLACE_GROUP_DM",
    "name": "Orbit team"
  },
  "direct": {
    "id": "feed_REPLACE_DIRECT_DM",
    "name": "Ava & Ben"
  }
};

export const supportByUser: Record<string, string> = {
  "ava": "feed_REPLACE_SUPPORT_AVA",
  "ben": "feed_REPLACE_SUPPORT_BEN",
  "cara": "feed_REPLACE_SUPPORT_CARA"
};

export const productId = "prod_REPLACE_RUN_SETUP";

export const knownUserIds = demoUsers.map((u) => u.userId);
export function isKnownUser(userId: string): boolean {
  return knownUserIds.includes(userId);
}
