// AUTO-GENERATED by scripts/setup-prod.mjs. Do not edit by hand.
// Placeholder state: set WHOP_PROD_* in .env.local and run `npm run setup:prod`
// against a dedicated production company to provision the live embed and
// regenerate this file.
//
// Public ids only (company / user / channel). The production API KEY is a secret
// and lives only in .env.local + Vercel env, never here.

export interface DemoUser {
  key: string;
  name: string;
  userId: string;
}

// True once the production company has been provisioned. The live-element
// section renders a "coming soon" placeholder while this is false.
export const provisioned = false;
export const companyId = "";
export const ownerUserId = "";

export const demoUsers: DemoUser[] = [];

export const channel = {
  "id": "",
  "experienceId": "",
  "name": "General"
};

export const knownUserIds = demoUsers.map((u) => u.userId);
export function isKnownUser(userId: string): boolean {
  return knownUserIds.includes(userId);
}
