import { doc, p, h2, ul, paywallBreak, type TipTapDoc } from "./tiptap";

export interface SeedStory {
  slug: string;
  authorHandle: string;
  title: string;
  subtitle: string;
  topics: string[];
  visibility: "FREE" | "PLUS";
  body: TipTapDoc;
  hasCover: boolean;
  publishedDaysAgo: number;
}

export const SEED_STORIES: SeedStory[] = [
  // ─────────────────────────── Maya Chen ────────────────────────────
  {
    slug: "component-library-i-wish-id-built",
    authorHandle: "mayachen",
    title: "The component library I wish I'd built in 2019",
    subtitle: "Five years on, here's what would survive the rebuild — and what I'd happily throw away.",
    topics: ["design", "ux"],
    visibility: "FREE",
    hasCover: true,
    publishedDaysAgo: 4,
    body: doc(
      p("Every component library I've worked on has a layer of sediment you can read like rings on a tree. There's the initial era of optimism, where every button has three variants and a comment explaining why. There's the middle period of compromise, where someone added a fourth variant on a Friday and nobody ever pruned it. And then there's the present — where roughly 40% of the code exists because someone, somewhere, once needed it for a single launch."),
      p("If I rebuilt mine today, here's what I'd keep, and here's what I'd quietly retire."),
      h2("What I'd keep"),
      p("The two-token system. Semantic tokens (surface, on-surface, accent) on top of a primitive palette. It's the most boring decision I ever made and the one that paid the most dividends, because designers and engineers ended up speaking the same vocabulary for free."),
      p("Composition over configuration. Five small primitives that snap together beat one prop-heavy Card with sixteen booleans. I'm convinced the boolean explosion is the single biggest reason design systems calcify."),
      h2("What I'd retire"),
      p("Every component whose name starts with the team that needed it. The PricingCallout. The OnboardingHero. None of them ever became reusable. They became museums."),
      p("Strict variants. Every \"size: 'sm' | 'md' | 'lg'\" prop is a tiny argument that compounds. I'd swap to a spacing scale and let composition do the rest."),
      p("If I had to put it on a t-shirt: build the primitives, name them after what they are, and resist the urge to ship a component for every screenshot someone Slacks you."),
    ),
  },
  {
    slug: "why-reusable-is-wrong-for-design-tokens",
    authorHandle: "mayachen",
    title: "Why \"reusable\" is the wrong goal for design tokens",
    subtitle: "The token system that lasted wasn't the one designed to be reused. It was the one designed to be composed.",
    topics: ["design", "programming"],
    visibility: "PLUS",
    hasCover: true,
    publishedDaysAgo: 9,
    body: doc(
      p("Somewhere around the third design system I built, I noticed the same pattern: we'd start by designing tokens to be reused, and end by quietly inventing a new layer on top of them so the team could actually ship things."),
      p("Reuse, it turns out, is a deceptive goal. It optimizes for the moment the token is created, not the months it has to survive."),
      h2("Reuse vs. composition"),
      p("A reusable token says: \"Use this exact value everywhere.\" A composable token says: \"Use this primitive, scoped by intent.\" The first feels safer. The second is what actually scales."),
      p("Compare the two:"),
      ul(
        "Reusable: --color-blue-600 is your CTA. Everyone uses it. One day marketing wants a campaign accent.",
        "Composable: --color-accent-default is your CTA, mapped to blue-600. Marketing's campaign is --color-accent-campaign. Same primitives, different intent.",
      ),
      p("Reuse pushes the conflict to the people writing components. Composition resolves it at the system layer."),
      paywallBreak(),
      h2("The intent layer"),
      p("Here's what I now do on day one of any token system: define an intent layer before any color. Surface, on-surface, accent, accent-on, warning, success, divider, overlay. That's it. Eight intents. Designers spec against intents. Primitives map to them."),
      p("It sounds bureaucratic until you watch a team rebrand in an afternoon without touching a single component file."),
      h2("The test that matters"),
      p("Ask any senior designer: \"If we changed our brand color tomorrow, how many components would need touching?\" If the answer is more than zero, your tokens are reusable, not composable. And reusable, alone, is not enough."),
    ),
  },
  {
    slug: "four-question-audit-empty-states",
    authorHandle: "mayachen",
    title: "The 4-question audit I run on every empty state",
    subtitle: "Empty states are where users meet your judgment. Most teams treat them like an afterthought.",
    topics: ["ux", "productivity"],
    visibility: "FREE",
    hasCover: true,
    publishedDaysAgo: 21,
    body: doc(
      p("Empty states are the most undervalued surface in product design. They're where new users meet your judgment for the first time, and where existing users meet your respect for their time."),
      p("Every empty state I review gets the same four questions."),
      h2("1. Is this empty because the user hasn't done anything yet, or because something failed?"),
      p("These need entirely different treatments. The first invites action. The second explains what went wrong and what to try. Conflating them is the single most common empty-state bug I see."),
      h2("2. What is the single most useful thing this user could do right now?"),
      p("Not three things. One. Empty states with three CTAs of equal weight are paralysis machines. Pick the action that helps the most people the most of the time, and make everything else secondary."),
      h2("3. Does the copy assume context the user doesn't have?"),
      p("\"Add your first widget\" is fine if I know what a widget is. If I just signed up, it's noise. Read every empty-state string while pretending you've never seen the product. If you have to squint, rewrite."),
      h2("4. Is there a chance the user is here because they expected something to be here?"),
      p("If yes, your job is to be a translator. \"Filter applied — no results matched.\" \"You've cleared all completed tasks.\" These are empty states with a story, and stories deserve sentences, not punctuation marks."),
      p("Empty states are tiny. The judgment they communicate is not."),
    ),
  },
  {
    slug: "designing-for-wrong-button-clicks",
    authorHandle: "mayachen",
    title: "Designing for the user who clicks the wrong button",
    subtitle: "Forgiveness is a feature. We spec it too rarely.",
    topics: ["ux", "self-improvement"],
    visibility: "FREE",
    hasCover: true,
    publishedDaysAgo: 33,
    body: doc(
      p("The first design crit I ran where someone got genuinely upset was about an undo affordance. The argument was familiar: \"If we add undo, users will be careless.\" I think about that argument often. I have come to believe it is exactly backwards."),
      p("Forgiveness in interface design isn't permission to be sloppy. It's an acknowledgment that humans are, fundamentally, the operating system you're running on."),
      h2("The three forgiveness primitives"),
      p("Confirm, undo, and recover. Most teams use confirm and call it a day. Confirmation dialogs are the cheapest possible forgiveness — they don't require state, just a friction surface."),
      p("But undo is where the real respect lives. Undo says: I expect you to take action quickly, and I expect that sometimes you'll be wrong, and I've built for both."),
      p("And recovery — quietly restoring data the user thought they lost — is the highest form. Most teams never get there, because it requires infrastructure decisions made months before the affordance shows up."),
      h2("The forgiveness budget"),
      p("Every interaction has an implicit forgiveness budget. A side-project app can lean on confirm dialogs. A medical or financial product needs undo and recovery on the same surface, because the cost of being wrong is asymmetric."),
      p("Before you ship any destructive action, ask: what does the user lose if they're wrong, and what's the cheapest mechanism that lets them be wrong without losing it? That's the design problem. Everything else is just a button."),
    ),
  },
  {
    slug: "year-of-design-crits-twelve-lessons",
    authorHandle: "mayachen",
    title: "A year of design crits, in 12 lessons",
    subtitle: "What I learned running weekly critiques across four product teams — and how the room changed when I changed the format.",
    topics: ["design", "career"],
    visibility: "PLUS",
    hasCover: true,
    publishedDaysAgo: 48,
    body: doc(
      p("For most of last year I ran a weekly design critique across four product teams. About thirty designers, forty minutes per session, every Thursday. I kept notes the whole time. Here's what I'd put on the wall if I were starting over."),
      h2("Lessons 1–6: format"),
      p("1. The presenter never speaks first. Whoever is presenting stays quiet for the first sixty seconds while the room reads the work. That single rule changed our crits more than any other change."),
      p("2. \"What's the question you're bringing?\" beats \"What did you make?\" Critiques are not show-and-tell. They are answerable."),
      p("3. Limit live screen-sharing. Send the link an hour before. The crit is for the discussion, not the page-load."),
      p("4. Two-minute timer on each piece of feedback. Long monologues kill the room."),
      p("5. Senior designers speak last. The juniors will reflexively defer to whoever spoke first, every time."),
      p("6. End with a written summary, not a vibe."),
      paywallBreak(),
      h2("Lessons 7–12: the room"),
      p("7. The quiet designer is usually the most useful. Build a rotation that surfaces them."),
      p("8. Critique tone is a leadership problem, not a culture problem. Set it explicitly in week one or watch it drift."),
      p("9. Don't crit unfinished work. Crit decisions, not pixels."),
      p("10. If three different designers give the same feedback, it's not feedback — it's a finding. Treat it differently."),
      p("11. The best crit I attended ended with: \"I think you've made a great solution to the wrong problem.\" That sentence is the highest service a critique can offer."),
      p("12. Stop the meeting when it's done. Forty minutes is the goal, not the target."),
    ),
  },

  // ─────────────────────────── Tom Whitfield ────────────────────────────
  {
    slug: "one-page-tech-spec-that-scaled",
    authorHandle: "tomwhitfield",
    title: "The one-page tech spec that scaled with us",
    subtitle: "A template, the rationale, and the five times I'd happily deviate from it.",
    topics: ["programming", "product-management"],
    visibility: "PLUS",
    hasCover: true,
    publishedDaysAgo: 6,
    body: doc(
      p("Two years ago I introduced a one-page tech spec template at a startup growing fast enough that nobody had time to read longer ones. We're still using it. Engineers have rewritten it, but the shape has held."),
      h2("The template"),
      ul(
        "Problem. What are we solving, in two sentences. No history.",
        "Proposed solution. The headline, then the smallest diagram that explains it.",
        "Alternatives considered. Two or three, with why we're not choosing them.",
        "Open questions. The genuine ones.",
        "Rollout. What ships first, what's reversible, who's on call.",
      ),
      p("That's it. One page, five headers, no appendices. The discipline isn't writing the spec — it's resisting the urge to make it two pages."),
      paywallBreak(),
      h2("The five times I'd happily deviate"),
      p("1. Database migrations. You need more space to show the schema diff and the backfill plan. One page is dishonest here."),
      p("2. Anything touching authentication. The threat model needs its own section, full stop."),
      p("3. Cross-team dependencies you don't control. The spec needs an explicit \"who owns what\" matrix or it becomes a finger-pointing artifact later."),
      p("4. First major feature for a new team. The longer spec is partly for the work and partly for the team to learn each other's writing styles."),
      p("5. Anything you're proposing to delete. Counterintuitively, deletions need more spec than additions, because the cost of being wrong is louder."),
      p("Outside those five, the one-page rule has held up across forty-something specs and counting. The constraint is the feature."),
    ),
  },
  {
    slug: "what-junior-engineers-want",
    authorHandle: "tomwhitfield",
    title: "What junior engineers actually want from their lead",
    subtitle: "I surveyed thirty of them last quarter. The answers were not what their managers expected.",
    topics: ["career", "programming"],
    visibility: "FREE",
    hasCover: true,
    publishedDaysAgo: 14,
    body: doc(
      p("Last quarter I helped a few engineering managers run a short, anonymous survey: what do you want from your lead that you're not getting? About thirty junior and mid-level engineers answered. The patterns surprised the managers."),
      h2("What didn't surprise anyone"),
      p("More feedback. More clarity on what \"good\" looks like at their level. More technical context on why we're building what we're building."),
      h2("What did surprise the managers"),
      p("1. They wanted their lead to write more code, not less. Not because they thought their lead needed to ship features — they wanted to see how their lead approached a hard problem in the same codebase, in the same week. Pull requests as pedagogy."),
      p("2. They wanted protected time, not protected meetings. The most common complaint wasn't \"too many meetings.\" It was \"too many short context-switches in a row.\" One engineer described it as \"my calendar looks fine on paper and feels like a stress test.\""),
      p("3. They wanted disagreement, but with the manager naming what's at stake. \"You can push back on me — just tell me whether this is a hill or a preference.\" That phrasing came up four separate times."),
      p("4. They wanted to be the second person to break the thing, not the first. Pair with me, watch me make a mistake, then I'll make the next one."),
      p("If you're a manager reading this and any of these feel novel, they're free to act on. Just ask your team directly. You'll get a better answer than this article."),
    ),
  },
  {
    slug: "on-call-shouldnt-be-a-punishment",
    authorHandle: "tomwhitfield",
    title: "On-call shouldn't be a punishment",
    subtitle: "Building a rotation that protects the humans on it — without making the rest of the team carry the slack.",
    topics: ["programming", "career"],
    visibility: "FREE",
    hasCover: true,
    publishedDaysAgo: 27,
    body: doc(
      p("On-call is the workplace tradition with the worst public-relations problem in engineering. Half the team treats it like a tax. The other half treats it like a hazing ritual. Both teams are wrong, and the fix is not complicated, just unglamorous."),
      h2("The deal"),
      p("A humane on-call rotation has three properties. First, the engineer on call is not also expected to ship a feature that week. They're a firefighter; you don't expect firefighters to also paint the firehouse. Second, an alert at 3 a.m. earns you the next morning off, no questions, no Slack message of approval needed. Third, every page becomes a ticket, and every ticket becomes a decision: is this alert telling us something we need to know, or is it noise we've been tolerating?"),
      h2("The cultural fix"),
      p("The team treats the on-call engineer like the most senior person in the room that week. They are. They have more context on what's actually breaking than anyone else. Their judgment about what to fix first should be respected without debate."),
      p("And the manager runs the on-call retro every two weeks. Not the engineers. The manager. Because the unglamorous truth about on-call is that most of its pain comes from decisions made months earlier — service ownership, alert thresholds, runbook quality — and only management can change those."),
      p("Get those three pieces right and on-call stops being the rotation everyone dreads. It becomes the week you learn the most."),
    ),
  },
  {
    slug: "case-for-shipping-the-boring-version",
    authorHandle: "tomwhitfield",
    title: "The case for shipping the boring version first",
    subtitle: "A short meditation on scope, ego, and the long compound interest of shipping.",
    topics: ["productivity", "programming"],
    visibility: "FREE",
    hasCover: true,
    publishedDaysAgo: 41,
    body: doc(
      p("Every engineer I've worked with has, at some point, sat in front of a design and silently decided to make it just a little more interesting than what was scoped. We dress it up as \"future-proofing.\" Sometimes it is. Mostly it's the part of us that wants the work to be ours."),
      p("Here is the boring case for shipping the boring version first."),
      h2("The compound math"),
      p("A boring v1 lets the team learn whether the feature matters before you've invested in the ambitious version. Five out of ten boring v1s get killed in the next sprint, because nobody used them. You just bought back two weeks per killed feature."),
      p("The remaining five graduate to v2 — but now they graduate with usage data, and v2 is informed by what real users do, not what you imagined they'd do. That feedback loop is worth more than any architectural cleverness you could've added in v1."),
      h2("The ego cost"),
      p("This is the part nobody writes about. Shipping the boring version means resisting the part of you that wants the code to be admired. The good news is that shipping itself becomes admirable, over enough cycles. Engineers known for shipping accumulate more interesting problems than engineers known for craft. Eventually you get to do both."),
      p("Ship the boring version. Then ship the next thing. The interesting code is downstream of the cycles."),
    ),
  },
  {
    slug: "code-review-as-writing-exercise",
    authorHandle: "tomwhitfield",
    title: "Code review as a writing exercise",
    subtitle: "Treat your review comments like editorial. The codebase improves. So do you.",
    topics: ["programming", "writing"],
    visibility: "PLUS",
    hasCover: true,
    publishedDaysAgo: 56,
    body: doc(
      p("The most underrated improvement to my code reviews didn't come from a tool or a checklist. It came from treating each comment like a sentence in a magazine article — meant to be read, persuasive, kind, and finishable."),
      h2("Three rewrites I do, every time"),
      p("First pass: I write what I think. This is the angry pass, the one that says \"why is this in a setTimeout.\" Nobody sees this pass."),
      p("Second pass: I make it diagnostic. \"This setTimeout will resolve after the parent unmounts; the cleanup function references state that no longer exists.\" Now the comment says what's wrong, not how I feel about it."),
      p("Third pass: I add the question. \"Is there a reason this can't be a useEffect with a cleanup function?\" The question moves it from monologue to dialogue."),
      paywallBreak(),
      h2("What changed downstream"),
      p("Three things, in this order. First, my comments stopped getting defensive replies. People answer questions more easily than they accept verdicts."),
      p("Second, junior engineers started writing better PRs because they could pattern-match the shape of a useful comment. Code review became a vehicle for teaching writing without it being a writing class."),
      p("Third — and this took me a year to notice — my own technical writing got tighter. The discipline of diagnosing-then-questioning in a code review is the same discipline that produces a useful tech spec. The constraint on the comment line is the same constraint on the spec page."),
      p("Code review is the highest-frequency writing exercise most engineers ever do. Treat it like one."),
    ),
  },

  // ─────────────────────────── Priya Raman ────────────────────────────
  {
    slug: "saas-made-4300-actual-spreadsheet",
    authorHandle: "priyaraman",
    title: "My SaaS made $4,300 last month. Here's the actual spreadsheet.",
    subtitle: "Real revenue, real costs, real hours. No course at the end.",
    topics: ["money", "startups"],
    visibility: "PLUS",
    hasCover: true,
    publishedDaysAgo: 11,
    body: doc(
      p("Public revenue posts on this platform tend to lean two ways: triumphant or confessional. This one is going to be neither. It's a spreadsheet."),
      h2("Revenue"),
      ul(
        "Recurring subscriptions: $3,840 (about 110 paying customers, weighted toward the $29 tier)",
        "One-time annual prepays: $460 (two customers prepaying at a small discount)",
        "Total MRR: roughly $3,950, with the rest as one-off cash",
      ),
      p("Net new customers last month: nine. Churned: three. Net: six. That's a slower month than the one before. I have stopped reading anything into single months."),
      h2("Costs"),
      ul(
        "Hosting and infra: $312",
        "Email and transactional: $74",
        "Payment processing: about 3.1% blended ($133)",
        "Accountant retainer (monthly): $200",
        "Software I actually use: $61",
      ),
      paywallBreak(),
      h2("What's not in the spreadsheet"),
      p("Hours worked: probably 90 across the month. Hourly cost if I were charging consulting rates: I won't do that math because it isn't honest. I'd be at that desk anyway."),
      p("The other thing not in the spreadsheet: the four customers who emailed me to ask how things were going. Three of them I wrote a sentence back to. One of them I wrote a paragraph to, because she'd been a customer for fourteen months and that deserves more than a sentence. That paragraph is the part of the month I'd put on a t-shirt."),
      h2("The honest takeaway"),
      p("$4,300 is not a story. It's a Tuesday. A solo SaaS that pays for itself and one good vacation a year is, statistically, an outlier. I'm grateful for it. I am not selling anyone a course on how to get one. There isn't one. You write for a long time and you don't quit."),
    ),
  },
  {
    slug: "writing-as-distribution-channel",
    authorHandle: "priyaraman",
    title: "Writing as a distribution channel, finally explained",
    subtitle: "How essays drove 60% of signups last year — and the three habits that turned writing from a hobby into a flywheel.",
    topics: ["writing", "startups"],
    visibility: "FREE",
    hasCover: true,
    publishedDaysAgo: 17,
    body: doc(
      p("A founder I respect once told me, half-laughing: \"Distribution is just writing, plus patience.\" I rolled my eyes at the time. I now think it's the single most useful sentence I've heard about marketing."),
      h2("The math, the honest version"),
      p("Last year, sixty percent of my signups came from organic essays I'd written over the previous two years. Roughly half of those came from three essays. That ratio scares people, but it's typical. Distribution through writing is a fat-tail bet. Most of what you publish does nothing. A few pieces do everything."),
      h2("The three habits"),
      p("1. Write the piece that's specifically useful to a person you'd want as a customer. Not \"my industry.\" One person, one role, one specific problem. The temptation to broaden is the temptation that produces forgettable essays."),
      p("2. Publish on a schedule you can keep on your worst week. For me that's every other Sunday. Not every Sunday — every other. The schedule's job is to remove the negotiation."),
      p("3. Treat the title like 40% of the work. Most readers see only the title. If the title doesn't earn the click, the rest is invisible."),
      h2("What writing is not"),
      p("It is not a content strategy. It is not a funnel. It is a slow, accumulating answer to a question your future customers haven't yet asked you. If you can be patient enough to write something useful instead of something clever, you eventually become one of the people they read."),
      p("Distribution is just writing, plus patience. He was right.")
    ),
  },
  {
    slug: "honest-case-for-staying-solo",
    authorHandle: "priyaraman",
    title: "The honest case for staying solo",
    subtitle: "Why I turned down a term sheet last spring — and what it cost.",
    topics: ["startups", "self-improvement"],
    visibility: "FREE",
    hasCover: true,
    publishedDaysAgo: 30,
    body: doc(
      p("Last spring I had a real, signable term sheet in front of me. A small fund, a clean structure, a partner I respected and wanted to keep respecting. I sat with it for a week. I said no. This is the part I've been quiet about until now."),
      h2("What I traded away"),
      p("Three things, mostly. Speed: I could have hired a designer and a customer-success person and probably doubled the business in eighteen months. Runway-as-permission: the freedom to take a bigger swing without watching my own checking account. And the comfort of a peer who's done this before — investors are people who answer your worst-week emails on Saturday morning."),
      h2("What I kept"),
      p("Calibration. The kind that comes from running a P&L that fits on a single screen. I make pricing decisions in fifteen minutes that a board would have spent six weeks on. That cycle time is the asset I was protecting."),
      p("And direction. The product I'd ship with two more people would not be the product I'd ship alone. Not better, not worse — different in ways I'd have eventually resented."),
      h2("Who I'm writing this for"),
      p("Not anyone considering raising. That's a decision with its own pros and cons and you should ignore me. I'm writing for the people who said no and then quietly wondered if they'd been small. You weren't being small. You were being specific."),
      p("Specificity is a perfectly good reason to run a small business."),
    ),
  },
  {
    slug: "three-customer-questions-from-doctors",
    authorHandle: "priyaraman",
    title: "3 customer-research questions I steal from doctors",
    subtitle: "Diagnostic interviewing, adapted for the awkward Tuesday morning Zoom call.",
    topics: ["product-management", "startups"],
    visibility: "FREE",
    hasCover: true,
    publishedDaysAgo: 38,
    body: doc(
      p("A friend who's a primary-care physician sent me a clinical interview guide last year. I started using three of its questions in customer research and they've quietly outperformed anything I picked up in a product course."),
      h2("1. \"Walk me through the last time this happened.\""),
      p("Specific. Past tense. Not what they'd do in general — what they did, in the last specific instance. Generalities are the worst possible source of product signal because everyone optimizes their own behavior in retrospect. The last specific time has texture."),
      h2("2. \"What were you doing right before that?\""),
      p("This is the question that produces the actual problem statement. Customers are rarely solving the thing they think they're solving. They're solving the thing that happened ten minutes before."),
      h2("3. \"What would have to be true for you to not have called?\""),
      p("Or, in software terms: what would have to be true for you to not have signed up? This is the inversion that finds the threshold. It also flushes out the substitutes — the spreadsheets, the Slack workarounds, the friend they texted instead."),
      p("Three questions, asked in order, with silence after each. Most of the value of a customer interview is the silence, not the words."),
    ),
  },

  // ─────────────────────────── James Okafor ────────────────────────────
  {
    slug: "promotion-isnt-a-reward-its-a-rebid",
    authorHandle: "jamesokafor",
    title: "Promotion isn't a reward. It's a re-bid.",
    subtitle: "The reframe that changed how my coaching clients prepare for the conversation — and how they survive the first six months after it.",
    topics: ["career", "self-improvement"],
    visibility: "PLUS",
    hasCover: true,
    publishedDaysAgo: 8,
    body: doc(
      p("Most of my coaching clients arrive at the promotion conversation believing one thing: that promotion is a reward for the last twelve months of work. I spend a meaningful portion of our first session trying to dislodge that idea."),
      p("Promotion is not a reward. It is a re-bid."),
      h2("What I mean"),
      p("A reward is something handed to you for what you've already done. It is backward-looking. It is also conclusive — once granted, the matter is closed."),
      p("A re-bid is a new contract for a new job. It is forward-looking. It does not honor the last twelve months so much as it predicts the next eighteen. And it is contestable, because the company is making a guess about you and your job is to make that guess feel safe."),
      paywallBreak(),
      h2("How the reframe changes the conversation"),
      p("Clients who treat the meeting as a reward arrive with a list of accomplishments. Clients who treat it as a re-bid arrive with a thesis about what the next role looks like and the evidence that they're already operating inside it."),
      p("The latter conversation goes meaningfully better. Not because the person did more work, but because the framing matches what the decision-maker is actually trying to do."),
      h2("The six months after"),
      p("Here's the part nobody warns you about. The first six months after a promotion is the period of highest re-bid risk you'll ever have at that company. Your peers are watching to see if the bet was wrong. Your manager is, too, even if they wouldn't put it that way."),
      p("Spend that period proving the prediction was correct. Not by working harder — by visibly operating at the new altitude. The promotion was the offer. The six months are the close."),
    ),
  },
  {
    slug: "status-update-your-boss-will-read",
    authorHandle: "jamesokafor",
    title: "How to write a status update your boss will actually read",
    subtitle: "Three lines, in this order. That's the whole template.",
    topics: ["writing", "productivity"],
    visibility: "FREE",
    hasCover: true,
    publishedDaysAgo: 19,
    body: doc(
      p("Most weekly status updates are written for the writer, not the reader. They are exhaustive, chronological, and unranked. They have the structure of a confession. A confession is the wrong format for a workplace artifact your manager has eight of, every Monday morning."),
      p("Try this instead. Three lines, in this order."),
      h2("Line 1: Shipped"),
      p("One sentence on what you actually completed since the last update. Not what you worked on. Completed. If nothing completed, write \"Nothing shipped this week\" and then explain why on line two."),
      h2("Line 2: Blocked / Risks"),
      p("One sentence on what's in your way, named. \"Waiting on legal on the data-retention question\" is useful. \"Some stuff slowed down\" is noise."),
      h2("Line 3: Next"),
      p("One sentence on what you'll ship next, with a concrete date if possible. The date is what separates a status update from a hope."),
      p("That's the whole template. Three lines. Forty seconds to write. Six seconds to read. Compounded across a year, it's the difference between a manager who knows what you're working on and a manager who has to guess."),
      p("If your team's culture demands more context, write the three lines first, then add. The discipline is in writing the headline before the elaboration."),
    ),
  },
  {
    slug: "decision-journal-seven-years",
    authorHandle: "jamesokafor",
    title: "The decision journal I've kept for seven years",
    subtitle: "The template I started in 2019, three real entries lightly anonymized, and the one rule I broke that I now regret.",
    topics: ["self-improvement", "productivity"],
    visibility: "FREE",
    hasCover: true,
    publishedDaysAgo: 34,
    body: doc(
      p("Seven years ago I started keeping a decision journal. Not a regular journal — a journal of the specific moments I made a decision that mattered, recorded before I knew how it would turn out. It is, by a considerable margin, the most useful thing I've kept."),
      h2("The template"),
      ul(
        "The decision, in one sentence.",
        "What I believe will happen if I do it.",
        "What I believe will happen if I don't.",
        "What I'd need to be wrong about to regret the choice.",
        "The single biggest thing I'm uncertain about.",
      ),
      p("Five lines. I write them in three minutes. The discipline isn't the writing — it's writing it before the result is known."),
      h2("Why this matters"),
      p("Memory is generous to past you. Without a journal, your brain quietly rewrites every decision to look like you knew it would work out. You lose the ability to calibrate. The journal is a forensic tool against your own narrative."),
      h2("The rule I broke, once"),
      p("There's one rule I'd put above the others: don't read old entries while making a new decision. They will pull you. The journal is for after, not during. I broke this rule once, on a job offer in 2022. I let an old entry about turning down a similar role color the new decision. The two situations weren't comparable. The decision was worse for it."),
      p("Decision journals are a long game. Yours will be most useful in year five. Start year five now.")
    ),
  },
  {
    slug: "what-i-tell-every-consultant",
    authorHandle: "jamesokafor",
    title: "What I tell every consultant on day one",
    subtitle: "A short letter to the version of me who took the offer twelve years ago.",
    topics: ["career", "books"],
    visibility: "FREE",
    hasCover: true,
    publishedDaysAgo: 49,
    body: doc(
      p("Dear new consultant,"),
      p("Congratulations. You've taken a job that will teach you, very fast, three things almost nobody else gets to learn in their twenties: how to read a business in an afternoon, how to disagree with a senior person without losing the room, and how to write a paragraph that holds up under interrogation."),
      p("Those three things will pay you for the rest of your career. They will also, occasionally, ruin a vacation. Both are true."),
      p("A few notes from twelve years out."),
      p("Be the person on the team who reads the deck out loud the night before. There is a specific, recoverable category of error that only surfaces when you say the words. You will catch them. Your seniors will notice."),
      p("Take notes by hand, at least for the first year. Not because handwriting is magical — because the friction of writing slowly forces you to translate, and translation is what consulting is."),
      p("Ask for the boring assignments. The interesting ones come with senior partners attached, and you'll be ornamental on those. The boring ones are where you'll actually learn to build a model, or write a section, or talk to a client without a script."),
      p("Finally: keep one book on your desk that has nothing to do with business. The job will try to crowd everything else out. Don't let it. The most interesting consultants I've worked with are interesting outside the slide-deck."),
      p("Good luck. — J."),
    ),
  },

  // ─────────────────────────── Eleni Markou ────────────────────────────
  {
    slug: "quiet-revolution-in-heat-pumps",
    authorHandle: "elenimarkou",
    title: "The quiet revolution in heat pumps",
    subtitle: "Why home electrification finally pencils out for ordinary households — and the three numbers that decide whether it does in yours.",
    topics: ["climate", "technology"],
    visibility: "FREE",
    hasCover: true,
    publishedDaysAgo: 5,
    body: doc(
      p("If you'd asked me five years ago whether heat pumps made financial sense for a typical household, I would have said \"in some climates, with subsidies, maybe.\" I'd say something different today. The technology has crossed a threshold quietly enough that most homeowners don't yet know it."),
      h2("What changed"),
      p("Three things, in order of impact."),
      p("First, cold-climate performance. Modern variable-speed heat pumps maintain meaningful capacity at temperatures most older systems couldn't touch. The old rule — \"heat pumps don't work below freezing\" — was true in 2010. It's not in 2025. Real-world data from cold-climate utility pilots has been the most surprising input here."),
      p("Second, installer fluency. Five years ago a heat-pump installation often went poorly because the contractor was learning on your house. The labor pool has matured. You can now ask for installers with twenty or more units under their belt in most metro areas."),
      p("Third, the math has finally stopped requiring a subsidy. Electricity prices have softened relative to natural gas in many regions. Combined with efficiency gains, the operating-cost calculation has crossed over for a growing share of households."),
      h2("The three numbers that decide your case"),
      p("Your kilowatt-hour cost. Your therm cost (or oil cost per gallon). And the coefficient of performance of the unit you're being quoted. The first two you already know. The third you can ask the contractor for — if they can't tell you, the conversation is over."),
      p("None of this is an instruction to electrify. It's an instruction to do the math, because for the first time in a long time, the math is different.")
    ),
  },
  {
    slug: "what-a-battery-actually-does",
    authorHandle: "elenimarkou",
    title: "What a battery actually does, with diagrams",
    subtitle: "Plain-English chemistry for the layperson. No equations. One useful mental model.",
    topics: ["science", "technology"],
    visibility: "FREE",
    hasCover: true,
    publishedDaysAgo: 13,
    body: doc(
      p("Almost everyone uses batteries every day. Almost no one I've asked outside materials science can describe, in a few sentences, what a battery actually does. This is mildly remarkable given how central they've become."),
      p("Here is the version I give to friends at dinner."),
      h2("The mental model"),
      p("Imagine a busy hallway between two rooms. One room is crowded with people. The other is nearly empty. People naturally want to move from the crowded room to the empty one. Open the door and they'll flow through, jostling each other as they go."),
      p("That flow — that's the current. The crowdedness difference between the two rooms — that's the voltage. And the hallway is the electrolyte: the substance that lets the people actually move."),
      p("When you discharge a battery, you're letting one side empty out into the other. When you charge it, you're pushing the people back. That's it. The chemistry varies. The model holds."),
      h2("Why this model is useful"),
      p("It explains why batteries lose capacity over time: each round trip wears down the doorway and the hallway. It explains why you can't pull power infinitely fast: there's only so much room in the hallway. And it explains why temperature matters: cold hallways slow everyone down."),
      h2("Where the model stops"),
      p("It does not explain why some chemistries dramatically outperform others. That involves real physics. But it gives you enough scaffolding that the real physics becomes legible the next time you read an article about it."),
      p("A useful model is one that's wrong in instructive ways. This one is wrong, instructively.")
    ),
  },
  {
    slug: "science-of-falling-asleep-faster",
    authorHandle: "elenimarkou",
    title: "The science of falling asleep faster (no TikTok hacks)",
    subtitle: "What the peer-reviewed literature actually says — and what it doesn't.",
    topics: ["health", "science"],
    visibility: "PLUS",
    hasCover: true,
    publishedDaysAgo: 22,
    body: doc(
      p("Every six months a new viral sleep tip makes the rounds. Most of them are unfounded. A few of them are real interventions wearing influencer clothing. Sorting one from the other requires reading the actual literature, which I've been doing for a year now."),
      p("None of this is medical advice. It is a literature summary."),
      h2("What's well-supported"),
      p("Consistent wake time. Of all the interventions studied, the one with the most robust replication is keeping the same wake time seven days a week, including weekends. Sleep onset latency improves on a timescale of weeks, not nights."),
      p("Light exposure within the first hour of waking. Morning light is the single largest cue for the circadian system. The evidence here is unusually solid for sleep research, which tends to be noisy."),
      p("Cool bedroom temperature. The window is roughly 18 to 20 degrees Celsius for most adults. The mechanism — a small drop in core body temperature signals sleep onset — is well-characterized."),
      paywallBreak(),
      h2("What's plausibly real but oversold"),
      p("Magnesium glycinate. There's a coherent mechanism and some positive trials, but the effect size is smaller than the marketing suggests. If you've already done the high-leverage interventions, it might help. It will not rescue an irregular schedule."),
      p("Weighted blankets. Mixed evidence. Some real signal in clinical populations. Less for healthy adults. Likely worth trying if you find it pleasant. Unlikely to be transformative."),
      h2("What's not real"),
      p("Most viral breathing patterns. The benefit, when it exists, is the relaxation response, which any slow breathing produces. The specific counts of \"4-7-8\" and similar are not load-bearing."),
      p("Any single supplement with a brand name and a personal story attached. The literature does not move at the speed of TikTok."),
      p("Boring works. Boring is also free.")
    ),
  },
  {
    slug: "walking-tour-of-kitchen-materials",
    authorHandle: "elenimarkou",
    title: "A walking tour of materials in your kitchen",
    subtitle: "Stainless, cast iron, ceramic — how they're made, why they behave the way they do, and which one is doing more work than you think.",
    topics: ["science", "culture"],
    visibility: "FREE",
    hasCover: true,
    publishedDaysAgo: 36,
    body: doc(
      p("Open the third drawer in your kitchen and you're looking at one of the most under-appreciated material-science exhibits in your house. Most of us inherited this drawer from our parents. Almost nobody knows what they're cooking with."),
      p("Here's the short tour."),
      h2("Stainless steel"),
      p("Iron, with chromium added so the surface forms a self-healing oxide layer that resists rust. The chromium is doing almost all the work; that's why \"surgical stainless\" and \"food-grade stainless\" differ mainly in chromium content. It's not a passive material. It's a material that's actively repairing itself every time you wash it."),
      h2("Cast iron"),
      p("Mostly iron with a higher carbon content than steel. The high carbon makes it brittle but also dramatically heat-retentive. The \"seasoning\" you've been told to maintain is, mechanically, a layer of polymerized fat — a thin plastic coat that you bonded to the surface through heat. Once you understand that, the maintenance rules stop feeling like folklore."),
      h2("Ceramic and stoneware"),
      p("Mineral clays, kiln-fired at temperatures hot enough to vitrify the structure. The glaze on top is a glass layer applied separately. Stoneware survives temperature swings better than porcelain because of larger crystal structures that absorb thermal stress."),
      h2("The one doing more work than you think"),
      p("Aluminum. Cheap, light, conducts heat better than almost anything you can afford, and is what most professional kitchens reach for first. The reason you don't see it celebrated is that it doesn't photograph as well as cast iron. The food does not care."),
      p("Open the drawer with new eyes. There's a century of metallurgy in there, hiding."),
    ),
  },

  // ─────────────────────────── Marcus Liang ────────────────────────────
  {
    slug: "why-great-albums-have-side-b-problem",
    authorHandle: "marcusliang",
    title: "Why every great album has a side B problem",
    subtitle: "Pacing, the sequencing decision most musicians get wrong, and why streaming has only made it harder.",
    topics: ["music", "culture"],
    visibility: "FREE",
    hasCover: true,
    publishedDaysAgo: 10,
    body: doc(
      p("There's a question I ask any musician friend who's about to release an album: \"What's your side B problem?\" If they look confused, I know we have something to talk about."),
      p("Every album of any length has a side B problem. The first side is the part everyone listens to. The second side is the part everyone is supposed to. The art is in making the second side worth the journey."),
      h2("The classic structure"),
      p("In the vinyl era, the constraints were physical. You had roughly twenty-two minutes per side, and the listener had to physically flip the record. That ritual created a natural pause that great producers used as a punctuation mark. Side A often closed with the most accessible song. Side B often opened with the most ambitious one. The flip was the dramatic pivot."),
      h2("What streaming changed"),
      p("On streaming, there is no flip. The listener can skip with their thumb mid-track, and every song competes individually for attention. This has not, as some critics worried, killed the album. It has changed what the side B problem looks like."),
      p("Now the side B problem is roughly track seven. That's where listeners decide whether you respect their time. Pad track seven and you lose the back half. Make it the album's secret weapon and you earn the full listen."),
      h2("The producers who solve it"),
      p("They sequence late. They don't decide the order until the very end, and they let the songs argue with each other. The artists who finalize the order in pre-production almost always have a sluggish back half. Sequence is a craft. Treat it like one."),
      p("Listen to your favorite album again, just for sequence. The reason it works is not the songs. It's the order."),
    ),
  },
  {
    slug: "unsung-craft-of-establishing-shot",
    authorHandle: "marcusliang",
    title: "The unsung craft of the establishing shot",
    subtitle: "Five seconds of geography that decide whether your story lands. A primer for non-filmmakers.",
    topics: ["film", "culture"],
    visibility: "FREE",
    hasCover: true,
    publishedDaysAgo: 26,
    body: doc(
      p("If you ask a film student which shot in a movie matters most, they'll usually name something dramatic. The right answer, for almost any film, is the first wide shot. The establishing shot is doing more work than any other frame in the picture, and most viewers will never know."),
      h2("What it's actually doing"),
      p("Three things, simultaneously. First, it gives you geography — where we are, the scale of the world, the relationship between the characters and their setting. Second, it sets the rules of the visual language: the color, the lighting style, the camera movement. And third, it makes a promise about pace. Slow establishing shot, slow film. Cut-heavy establishing shot, kinetic film."),
      p("Five seconds. Three jobs."),
      h2("How great filmmakers cheat with it"),
      p("They violate it on purpose. A film that opens with a tight close-up instead of a wide is announcing, deliberately, that the geography is going to come from inside the character, not the world. A film that opens with a stationary shot of a landscape and then slowly pushes in is telling you the world here is unmoving — humans are the only things that change."),
      p("Once you start noticing the establishing shot, you cannot unsee it. You'll find yourself fifteen seconds into a film already certain whether it's going to be good. You'll usually be right. Five seconds isn't much. It's the most expensive five seconds in the medium."),
    ),
  },
  {
    slug: "what-ultrarunning-taught-about-deep-work",
    authorHandle: "marcusliang",
    title: "What ultrarunning taught me about deep work",
    subtitle: "The discipline of the long mile, applied to the long page.",
    topics: ["sports", "productivity"],
    visibility: "PLUS",
    hasCover: true,
    publishedDaysAgo: 43,
    body: doc(
      p("I started running ultras at thirty-two for unflattering reasons. I wanted to feel like I was good at something physical, and I had the time. I have since finished four hundred-kilometer races, several shorter ones, and dropped from two. The most interesting thing I learned has nothing to do with running."),
      p("Ultrarunning is, fundamentally, an exercise in managing your own mind for a very long time. It turns out the techniques transfer."),
      h2("The pacing problem"),
      p("In a hundred-kilometer race, the first thirty kilometers are easy and feel like a betrayal. You're full of energy, you're surrounded by other runners going too fast, and the most disciplined thing you can do is hold back. Almost everyone who blows up later did so by running the first third too hard."),
      p("Deep work has the same shape. The first hour of a serious writing session feels too easy. You can produce a lot. The temptation is to keep producing. The discipline is to stop, because what you've written needs to be read back in a quiet room before the next thousand words go on top of it."),
      paywallBreak(),
      h2("The bonk and the rewrite"),
      p("Around kilometer sixty in an ultra, almost everyone bonks. Your blood sugar craters, your legs stop responding to your brain, and the mind starts producing reasons to quit that are remarkably specific. \"You haven't been training hard enough.\" \"This isn't actually what you wanted.\" \"Your knee is about to give.\""),
      p("Deep work has its own bonk. It arrives around the third hour, or around the fourth time you've reread a paragraph that won't come right. The mind produces equivalent excuses. \"You should never have committed to this piece.\" \"Maybe this isn't your subject.\""),
      p("In both cases, the answer is the same. Eat something. Walk for ten minutes. Then resume, slowly. The bonk is not information. It's weather."),
      h2("The finish"),
      p("At the end of an ultra, you don't feel triumphant. You feel calm. The same is true of finishing a long piece of writing. The reward is not what you imagine. It is a quiet sense of having paid attention for longer than felt possible. That, alone, is worth the training."),
    ),
  },
];
